# -*- coding: utf-8 -*-
"""letsupgrade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jynV_hxRGLC1s-xQODC73WTuFzcWkXDu
"""

value=int(input("enter a number: "))
if(value%2)==0:
  print(value,"is even")
else:
    print(value,"is odd")